[profile.default]
src = "src"
out = "out"
script = "script"
libs = ["lib"]
offline = false
solc-version = "0.8.22"
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
  'solidity-bytes-utils/=lib/solidity-bytes-utils',
  '@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/oapp',
  '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/protocol',
  '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/messagelib',
]

[profile.ci]
verbosity = 4

[rpc_endpoints]
canto-testnet = "https://canto-testnet.plexnode.wtf"
canto-mainnet = "https://canto.slingshot.finance/"
hardhat-node = "http://127.0.0.1:8545/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
